version: '3.8'

services:
  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default

    restart: "unless-stopped"

  node:
    build:
      context: ./server
      dockerfile: ./server/Dockerfile
    container_name: node
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./source:/source
      - /source/node_modules

    networks:
      - default
    restart: "unless-stopped"

networks:
  default:
    external: true
    name: nodejs-1

