version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "433:433"
    expose:
      - "80"
      - "433"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - default
    restart: "unless-stopped"

  node:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: node
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./source:/source
      - /source/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - default
    restart: "unless-stopped"

networks:
  default:
    external:
      name: nodejs


